# Generated by Django 3.1.7 on 2021-03-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IoT_sensor_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name=50)),
                ('humi', models.FloatField(verbose_name=50)),
                ('light', models.FloatField(verbose_name=50)),
                ('UV', models.FloatField(verbose_name=50)),
            ],
        ),
    ]
