# Generated by Django 3.1.7 on 2021-04-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_train_API', '0005_auto_20210327_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot_sensor_info',
            name='moisture',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
    ]
